# ==================================================
# Application
# ==================================================
spring:
  # =============================
  # Security - OAuth2 Resource Server (JWT)
  # =============================
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/fitness-app

  # ==================================================
  # Database (MongoDB)
  # ==================================================
  mongodb:
    uri: mongodb://localhost:27017/airecommendationfitness


  # ==================================================
  # Spring MVC
  # ==================================================
  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  # ==================================================
  # Kafka
  # ==================================================
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.messaging.event.ActivityCreatedEvent
        spring.json.trusted.packages: "com.fitness.aiservice.*"



# ==================================================
# Custom Application Settings
# ==================================================
app:
  debug-errors: true
  kafka:
    topics:
      activity-events: activity-events
  gemini:
    api-key: ${GEMINI_API_KEY}
    api-url: ${GEMINI_API_URL}


# ==================================================
# Eureka (Service Discovery)
# ==================================================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


# ==================================================
# External Services Configuration
# ==================================================
# ==================================================
# External Services Configuration
# ==================================================
services:
  activityservice:
    base-url: http://activityservice
    base-path: /api/v1/activities
    endpoints:
      find-by-id: /{activityId}

