# ==================================================
# Application
# ==================================================
spring:
  application:
    name: eureka


# ==================================================
# Server
# ==================================================
server:
  port: 8761


# ==================================================
# Eureka Server Configuration
# ==================================================
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
