# ==================================================
# Application
# ==================================================
spring:
  application:
    name: userservice


  # ==================================================
  # Client Server Config
  # ==================================================
  config:
    import: optional:configserver:http://localhost:9000

# ==================================================
# Server
# ==================================================
server:
  port: 4100
